# Setup

title: The Social Life of Neighborhoods
email: alex@collectivelymade.com
description: > # this means to ignore newlines until "baseurl:"
  A framework to measure neighborhood progress towards a more Social LIFE.
baseurl: "/social-life" # the subpath of your site, e.g. /blog
url: "http://alexanderussell.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Owner/author information
owner:
  name:           Alex Russell
  avatar:         avatar.png
  bio:            "Designer."
  email:          alex@collectivelymade.com
  twitter:        alexanderussell
  github:         alexanderussell
  instagram:      alexanderussell
  dribbble:       alexanderussell
  location:       "Lincoln, NE"